import { getFormatDateNow } from '../../../utils/format'

interface Props {
  name: string
  email: string
  dni: string
  os:string
  companyName: string
  url: string
  urlWhatsapp?: string
}

function getTimeString (date: Date) {
  const dateCopy = new Date(date)

  const mouths = [
    'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Setiembre', 'Octubre', 'Noviembre', 'Diciembre'
  ]

  return `${mouths[dateCopy.getMonth()]} ${dateCopy.getDate()}, ${dateCopy.getFullYear()}`
}

export default function getTemplateWelcomeInHouse ({ os, companyName, name, email, dni, urlWhatsapp }: Props) {
  const now = new Date()
  now.setHours(now.getHours() - 5)
  const dateString = getTimeString(now)

  const formatDate = getFormatDateNow()
  const formatCompanyName = companyName.toUpperCase()
  const formatOs = os.toUpperCase()
  const formatName = name.toUpperCase()

  // const extra = ' <p class="es-text-mobile-size-16" style="Margin:0;mso-line-height-rule:exactly;font-family:arial, \'helvetica neue\', helvetica, sans-serif;line-height:24px;letter-spacing:0;color:#333333;font-size:16px"><strong>LA ASISTENCIA DE LA SESIÓN SE REGISTRARÁ MEDIANTE EL INGRESO A SU AULA VIRTUAL<br></strong></p><p class="es-text-mobile-size-16" style="Margin:0;mso-line-height-rule:exactly;font-family:arial, \'helvetica neue\', helvetica, sans-serif;line-height:24px;letter-spacing:0;color:#333333;font-size:16px"><br></p>'
  const extra = ''
  // const horarios = '<p class="es-text-mobile-size-16 es-override-size" style="font-size: 16px; line-height: 250%"><strong>CRONOGRAMA</strong></p><p class="es-text-mobile-size-16 es-override-size" style="font-size: 16px; line-height: 150%"><strong>Fechas: </strong>10, 11, 13, 16, 18 y 20 de Diciembre</p><p class="es-text-mobile-size-16 es-override-size" style="font-size: 16px; line-height: 150%"><strong>Hora: </strong>07:00 p.m a 10:00 p.m</p>'
  const horarios = ''

  return `
  <!DOCTYPE html><html dir="ltr" xmlns="http://www.w3.org/1999/xhtml" xmlns:o="urn:schemas-microsoft-com:office:office" lang="es"><head><meta charset="UTF-8"><meta content="width=device-width, initial-scale=1" name="viewport"><meta name="x-apple-disable-message-reformatting"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta content="telephone=no" name="format-detection"><title>Bienvenido Inhouse</title> <!--[if (mso 16)]><style type="text/css"> a {text-decoration: none;}  </style><![endif]--><!--[if gte mso 9]><style>sup { font-size: 100% !important; }</style><![endif]--><!--[if gte mso 9]><noscript> <xml> <o:OfficeDocumentSettings> <o:AllowPNG></o:AllowPNG> <o:PixelsPerInch>96</o:PixelsPerInch> </o:OfficeDocumentSettings> </xml> </noscript>
<![endif]--><style type="text/css">.rollover:hover .rollover-first { max-height:0px!important; display:none!important;}.rollover:hover .rollover-second { max-height:none!important; display:block!important;}.rollover span { font-size:0px;}u + .body img ~ div div { display:none;}#outlook a { padding:0;}span.MsoHyperlink,span.MsoHyperlinkFollowed { color:inherit; mso-style-priority:99;}a.es-button { mso-style-priority:100!important; text-decoration:none!important;}a[x-apple-data-detectors],#MessageViewBody a { color:inherit!important; text-decoration:none!important; font-size:inherit!important; font-family:inherit!important; font-weight:inherit!important; line-height:inherit!important;}.es-desk-hidden { display:none; float:left; overflow:hidden; width:0; max-height:0; line-height:0; mso-hide:all;}@media only screen and (max-width:600px) {.es-m-p0r { padding-right:0px!important } .es-m-p20b { padding-bottom:20px!important }
 .es-p-default { } *[class="gmail-fix"] { display:none!important } p, a { line-height:150%!important } h1, h1 a { line-height:120%!important } h2, h2 a { line-height:120%!important } h3, h3 a { line-height:120%!important } h4, h4 a { line-height:120%!important } h5, h5 a { line-height:120%!important } h6, h6 a { line-height:120%!important } .es-header-body p { } .es-content-body p { } .es-footer-body p { } .es-infoblock p { } h1 { font-size:30px!important; text-align:left } h2 { font-size:24px!important; text-align:left } h3 { font-size:20px!important; text-align:left } h4 { font-size:24px!important; text-align:left } h5 { font-size:20px!important; text-align:left } h6 { font-size:16px!important; text-align:left } .es-header-body h1 a, .es-content-body h1 a, .es-footer-body h1 a { font-size:30px!important } .es-header-body h2 a, .es-content-body h2 a, .es-footer-body h2 a { font-size:24px!important }
 .es-header-body h3 a, .es-content-body h3 a, .es-footer-body h3 a { font-size:20px!important } .es-header-body h4 a, .es-content-body h4 a, .es-footer-body h4 a { font-size:24px!important } .es-header-body h5 a, .es-content-body h5 a, .es-footer-body h5 a { font-size:20px!important } .es-header-body h6 a, .es-content-body h6 a, .es-footer-body h6 a { font-size:16px!important } .es-menu td a { font-size:14px!important } .es-header-body p, .es-header-body a { font-size:14px!important } .es-content-body p, .es-content-body a { font-size:14px!important } .es-footer-body p, .es-footer-body a { font-size:14px!important } .es-infoblock p, .es-infoblock a { font-size:12px!important } .es-m-txt-c, .es-m-txt-c h1, .es-m-txt-c h2, .es-m-txt-c h3, .es-m-txt-c h4, .es-m-txt-c h5, .es-m-txt-c h6 { text-align:center!important }
 .es-m-txt-r, .es-m-txt-r h1, .es-m-txt-r h2, .es-m-txt-r h3, .es-m-txt-r h4, .es-m-txt-r h5, .es-m-txt-r h6 { text-align:right!important } .es-m-txt-j, .es-m-txt-j h1, .es-m-txt-j h2, .es-m-txt-j h3, .es-m-txt-j h4, .es-m-txt-j h5, .es-m-txt-j h6 { text-align:justify!important } .es-m-txt-l, .es-m-txt-l h1, .es-m-txt-l h2, .es-m-txt-l h3, .es-m-txt-l h4, .es-m-txt-l h5, .es-m-txt-l h6 { text-align:left!important } .es-m-txt-r img, .es-m-txt-c img, .es-m-txt-l img { display:inline!important } .es-m-txt-r .rollover:hover .rollover-second, .es-m-txt-c .rollover:hover .rollover-second, .es-m-txt-l .rollover:hover .rollover-second { display:inline!important } .es-m-txt-r .rollover span, .es-m-txt-c .rollover span, .es-m-txt-l .rollover span { line-height:0!important; font-size:0!important; display:block } .es-spacer { display:inline-table }
 a.es-button, button.es-button { font-size:18px!important; padding:10px 20px 10px 20px!important; line-height:120%!important } a.es-button, button.es-button, .es-button-border { display:inline-block!important } .es-m-fw, .es-m-fw.es-fw, .es-m-fw .es-button { display:block!important } .es-m-il, .es-m-il .es-button, .es-social, .es-social td, .es-menu { display:inline-block!important } .es-adaptive table, .es-left, .es-right { width:100%!important } .es-content table, .es-header table, .es-footer table, .es-content, .es-footer, .es-header { width:100%!important; max-width:600px!important } .adapt-img { width:100%!important; height:auto!important } .es-mobile-hidden, .es-hidden { display:none!important } .es-desk-hidden { width:auto!important; overflow:visible!important; float:none!important; max-height:inherit!important; line-height:inherit!important } tr.es-desk-hidden { display:table-row!important }
 table.es-desk-hidden { display:table!important } td.es-desk-menu-hidden { display:table-cell!important } .es-menu td { width:1%!important } table.es-table-not-adapt, .esd-block-html table { width:auto!important } .h-auto { height:auto!important } .img-4199 { width:200px!important } .es-text-2553 .es-text-mobile-size-16, .es-text-2553 .es-text-mobile-size-16 * { font-size:16px!important; line-height:150%!important } .img-8032 { width:200px!important } .es-text-2553 .es-text-mobile-size-16.es-override-size, .es-text-2553 .es-text-mobile-size-16.es-override-size * { font-size:16px!important; line-height:150%!important } .es-text-8982 .es-text-mobile-size-16, .es-text-8982 .es-text-mobile-size-16 * { font-size:16px!important; line-height:150%!important } }@media screen and (max-width:384px) {.mail-message-content { width:414px!important } }</style>
 </head> <body class="body" style="width:100%;height:100%;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;padding:0;Margin:0"><div dir="ltr" class="es-wrapper-color" lang="es" style="background-color:#F6F6F6"><!--[if gte mso 9]><v:background xmlns:v="urn:schemas-microsoft-com:vml" fill="t"> <v:fill type="tile" color="#f6f6f6"></v:fill> </v:background><![endif]--><table width="100%" cellspacing="0" cellpadding="0" class="es-wrapper" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;padding:0;Margin:0;width:100%;height:100%;background-repeat:repeat;background-position:center top;background-color:#F6F6F6"><tr><td valign="top" style="padding:0;Margin:0"><table cellspacing="0" cellpadding="0" align="center" class="es-content" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;width:100%;table-layout:fixed !important"><tr>
<td align="center" style="padding:0;Margin:0"><table cellspacing="0" cellpadding="0" bgcolor="#ffffff" align="center" class="es-content-body" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#ffffff;width:600px" role="none"><tr><td align="left" bgcolor="#003399" background style="padding:20px;Margin:0;background-color:#003399" data-custom-paddings="true"><!--[if mso]><table style="width:560px" cellpadding="0" cellspacing="0"><tr><td style="width:270px" valign="top"><![endif]--><table cellspacing="0" cellpadding="0" align="left" class="es-left" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left"><tr>
<td valign="top" align="center" class="es-m-p0r es-m-p20b" style="padding:0;Margin:0;width:270px"><table width="100%" cellspacing="0" cellpadding="0" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr><td align="center" style="padding:0;Margin:0;font-size:0px"><img src="https://ffrbvdx.stripocdn.email/content/guids/CABINET_ecc57152f936766c55ec45db3544c566f45f536a777eae126d096d01b046bf71/images/logodark.png" alt="" width="250" class="img-8032" style="display:block;font-size:14px;border:0;outline:none;text-decoration:none"></td> </tr></table></td></tr></table><!--[if mso]></td><td style="width:20px"></td><td style="width:270px" valign="top"><![endif]--><table cellpadding="0" cellspacing="0" align="right" class="es-right" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:right"><tr>
<td align="left" style="padding:0;Margin:0;width:270px"><table width="100%" role="presentation" cellpadding="0" cellspacing="0" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr><td align="right" class="es-text-8982" style="padding:0;Margin:0;padding-top:30px"><p class="es-text-mobile-size-16 es-m-txt-c" style="Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:32px;letter-spacing:0;color:#ffffff;font-size:16px"><strong>${dateString}</strong></p></td></tr> </table></td></tr></table><!--[if mso]></td></tr></table><![endif]--></td></tr></table></td></tr></table>
 <table cellspacing="0" cellpadding="0" align="center" class="es-header" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;width:100%;table-layout:fixed !important;background-color:transparent;background-repeat:repeat;background-position:center top"><tr><td align="center" style="padding:0;Margin:0"><table cellspacing="0" cellpadding="0" bgcolor="#ffffff" align="center" class="es-header-body" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#FFFFFF;width:600px"><tr><td align="left" data-custom-paddings="true" style="Margin:0;padding-top:35px;padding-right:30px;padding-bottom:35px;padding-left:30px"><table cellpadding="0" cellspacing="0" width="100%" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr>
<td align="center" valign="top" style="padding:0;Margin:0;width:540px"><table cellpadding="0" cellspacing="0" width="100%" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr><td align="left" class="es-text-2553" style="padding:0;Margin:0"><p class="es-text-mobile-size-16 es-override-size" style="Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:27px;letter-spacing:0;color:#333333;font-size:18px"><strong>Estimado estudiante</strong></p> <p class="es-text-mobile-size-16 es-override-size" style="Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:21px;letter-spacing:0;color:#333333;font-size:14px"><br></p>
<p class="es-text-mobile-size-16 es-override-size" style="Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:24px;letter-spacing:0;color:#333333;font-size:16px">Es un placer darle la bienvenida a la presente capacitación, financiada por la <strong>${formatCompanyName}</strong>, registrada en fecha <strong>${formatDate}</strong> ${formatOs.length > 0 ? `con código interno <strong>${formatOs}</strong>` : ''}</p>${horarios}<p class="es-text-mobile-size-16 es-override-size" style="Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:24px;letter-spacing:0;color:#333333;font-size:16px"><strong><br></strong></p> <p class="es-text-mobile-size-16 es-override-size" style="Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:24px;letter-spacing:0;color:#333333;font-size:16px">Ingrese y verifique la activación de sus accesos:</p>
<p class="es-text-mobile-size-16 es-override-size" style="Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:24px;letter-spacing:0;color:#333333;font-size:16px"><br></p> <p class="es-text-mobile-size-16 es-override-size" style="Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:24px;letter-spacing:0;color:#333333;font-size:16px"><strong>Paso 1:</strong> Hacer clic en: <a target="_blank" href="https://aula.desarrolloglobal.pe/login" style="mso-line-height-rule:exactly;text-decoration:underline;color:#003399;font-size:16px;line-height:24px">https://aula.desarrolloglobal.pe/login</a><br><br><strong>Paso 2:</strong> Digite:</p>
<p class="es-text-mobile-size-16 es-override-size" style="Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:24px;letter-spacing:0;color:#333333;font-size:16px"><strong>Usuario: </strong>${email}</p> <p class="es-text-mobile-size-16 es-override-size" style="Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:24px;letter-spacing:0;color:#333333;font-size:16px"><strong>Contraseña: </strong>${dni}</p><p class="es-text-mobile-size-16 es-override-size" style="Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:24px;letter-spacing:0;color:#333333;font-size:16px"><br></p>
<p class="es-text-mobile-size-16 es-override-size" style="Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:24px;letter-spacing:0;color:#333333;font-size:16px">Usted podrá encontrar en la plataforma:</p><ul style="font-family:arial, 'helvetica neue', helvetica, sans-serif;padding:0px 0px 0px 40px;margin-top:15px;margin-bottom:15px"> <li class="es-override-size es-text-mobile-size-16" style="color:#333333;margin:0px 0px 15px;font-size:16px;line-height:24px"><p class="es-text-mobile-size-16 es-override-size" style="Margin:0;mso-line-height-rule:exactly;mso-margin-bottom-alt:15px;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:24px;letter-spacing:0;color:#333333;font-size:16px;mso-margin-top-alt:15px">Material de cada sesión para descargar (Pestaña Material).</p></li> 
<li class="es-override-size es-text-mobile-size-16" style="color:#333333;margin:0px 0px 15px;font-size:16px;line-height:24px"><p class="es-text-mobile-size-16 es-override-size" style="Margin:0;mso-line-height-rule:exactly;mso-margin-bottom-alt:15px;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:24px;letter-spacing:0;color:#333333;font-size:16px">Evaluaciones</p></li> <li class="es-override-size es-text-mobile-size-16" style="color:#333333;margin:0px 0px 15px;font-size:16px;line-height:24px"><p class="es-text-mobile-size-16 es-override-size" style="Margin:0;mso-line-height-rule:exactly;mso-margin-bottom-alt:15px;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:24px;letter-spacing:0;color:#333333;font-size:16px">La clase realizada estará grabada para repasar.</p></li> </ul>
<p style="Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:21px;letter-spacing:0;color:#333333;font-size:14px"><br></p><p class="es-text-mobile-size-16 es-override-size" style="line-height:150%;font-size:16px">Asimismo, recibirá un mensaje desde el Aula Virtual con los detalles de acceso y una guía de uso. <strong>Recuerde que su asistencia se registrará automáticamente al ingresar al Aula Virtual.</strong></p><p class="es-text-mobile-size-16 es-override-size" style="Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:24px;letter-spacing:0;color:#333333;font-size:16px"><br></p>
${
    urlWhatsapp
    ? `
    <p class="es-text-mobile-size-16 es-override-size" style="Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:24px;letter-spacing:0;color:#333333;font-size:16px">Unirse al grupo de <strong>WhatsApp</strong> dando clic aquí:<a target="_blank" href="${urlWhatsapp}" style="mso-line-height-rule:exactly;text-decoration:underline;color:#003399;font-size:16px;line-height:24px"><strong> [Enlace al grupo]</strong></a></p><p style="Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:21px;letter-spacing:0;color:#333333;font-size:14px"><br></p>
    <p class="es-text-mobile-size-16" style="Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:24px;letter-spacing:0;color:#333333;font-size:16px">Por este medio recibirá las notificaciones del desarrollo de la clase. Evite salir del grupo hasta el término de las clases.</p><p class="es-text-mobile-size-16" style="Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:24px;letter-spacing:0;color:#333333;font-size:16px"><br></p>
    `
    : ''
  }
<p class="es-text-mobile-size-16" style="Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:24px;letter-spacing:0;color:#333333;font-size:16px">Verifique sus datos de certificación:</p><ul style="font-family:arial, 'helvetica neue', helvetica, sans-serif;padding:0px 0px 0px 40px;margin-top:15px;margin-bottom:15px"> 
<li style="color:#333333;margin:0px 0px 15px;font-size:14px;line-height:8px"><p class="es-text-mobile-size-16" style="Margin:0;mso-line-height-rule:exactly;mso-margin-bottom-alt:15px;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:20px;letter-spacing:0;color:#333333;font-size:16px;mso-margin-top-alt:15px"><strong>Nombres y Apellidos: </strong>${formatName}</p></li> <li style="color:#333333;margin:0px 0px 15px;font-size:14px;line-height:8px"><p class="es-text-mobile-size-16" style="Margin:0;mso-line-height-rule:exactly;mso-margin-bottom-alt:15px;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:8px;letter-spacing:0;color:#333333;font-size:16px"><strong>N° DNI: </strong>${dni}</p></li> </ul><p style="Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:21px;letter-spacing:0;color:#333333;font-size:14px"><br></p>
 <p class="es-text-mobile-size-16" style="Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:24px;letter-spacing:0;color:#333333;font-size:16px"><strong>RECOMENDACIONES</strong><br>En caso de que no haya usado <strong>ZOOM</strong> anteriormente, instale en la laptop o PC que usará para recibir clases desde aquí: <a href="https://zoom.us/download" style="mso-line-height-rule:exactly;text-decoration:underline;color:#003399;font-size:16px;line-height:24px">Instalar <strong>ZOOM</strong></a><br>Evite ingresar desde un móvil (smartphone).</p><p class="es-text-mobile-size-16" style="Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:24px;letter-spacing:0;color:#333333;font-size:16px"><br></p>
${extra}<p class="es-text-mobile-size-16" style="Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:24px;letter-spacing:0;color:#333333;font-size:16px"><strong>Al finalizar la capacitación:<br></strong>Usted obtendrá 1 CERTIFICADO A NOMBRE DE <strong>DESARROLLO GLOBAL</strong></p><p class="es-text-mobile-size-16" style="Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:24px;letter-spacing:0;color:#333333;font-size:16px"><br><strong>TÉRMINOS Y CONDICIONES</strong></p><ul style="font-family:arial, 'helvetica neue', helvetica, sans-serif;padding:0px 0px 0px 40px;margin-top:15px;margin-bottom:15px"> 
<li style="color:#333333;margin:0px 0px 15px;font-size:16px;line-height:24px"><p class="es-text-mobile-size-16" style="Margin:0;mso-line-height-rule:exactly;mso-margin-bottom-alt:15px;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:24px;letter-spacing:0;color:#333333;font-size:16px;mso-margin-top-alt:15px">Para recibir la certificación por aprobación, el alumno deberá resolver todas las evaluaciones y obtener un promedio superior a catorce (14). En caso contrario, se emitirá únicamente una constancia de participación.</p></li> 
<li style="color:#333333;margin:0px 0px 15px;font-size:16px;line-height:24px"><p class="es-text-mobile-size-16" style="Margin:0;mso-line-height-rule:exactly;mso-margin-bottom-alt:15px;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:24px;letter-spacing:0;color:#333333;font-size:16px">La entrega de certificaciones o constancias está sujeta al pago del servicio. Se pueden considerar excepciones en coordinación con el encargado de la entidad.</p></li> <li style="color:#333333;margin:0px 0px 15px;font-size:16px;line-height:24px"><p class="es-text-mobile-size-16" style="Margin:0;mso-line-height-rule:exactly;mso-margin-bottom-alt:15px;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:24px;letter-spacing:0;color:#333333;font-size:16px">La certificación física será entregada al coordinador designado por la entidad.</p></li> </ul>
 <p style="Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:21px;letter-spacing:0;color:#333333;font-size:14px"><br></p><p class="es-text-mobile-size-16" style="Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:32px;letter-spacing:0;color:#333333;font-size:16px">Con atentos saludos,</p><p class="es-text-mobile-size-16 es-override-size" style="Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:8px;letter-spacing:0;color:#333333;font-size:16px"><br></p><p class="es-text-mobile-size-16" style="Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:32px;letter-spacing:0;color:#333333;font-size:16px">Equipo de Capacitación</p></td></tr></table></td></tr></table></td></tr></table> </td></tr></table>
 <table align="center" cellspacing="0" cellpadding="0" class="es-content" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;width:100%;table-layout:fixed !important"><tr><td align="center" bgcolor="transparent" style="padding:0;Margin:0"><table align="center" cellpadding="0" cellspacing="0" bgcolor="#ffffff" class="es-content-body" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#FFFFFF;width:600px"><tr><td align="left" data-custom-paddings="true" style="padding:20px;Margin:0"><table cellpadding="0" cellspacing="0" width="100%" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr>
<td align="left" style="padding:0;Margin:0;width:560px"><table width="100%" role="presentation" cellpadding="0" cellspacing="0" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr><td align="left" style="padding:0;Margin:0"><table style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:white;font-family:-apple-system, BlinkMacSystemFont, 'segoe ui', Roboto, Helvetica, Arial, sans-serif, 'apple color emoji', 'segoe ui emoji', 'segoe ui symbol'" role="presentation"><tr><td style="padding:0;Margin:0"><img src="https://archivos-comunes.s3.amazonaws.com/2023/Foto+para+Firma+Dayana+Rivera.png" width="110" alt="perfil" height="110" style="display:block;font-size:14px;border:0;outline:none;text-decoration:none"></td>
 <td style="padding:0;Margin:0;border-left-width:9px;border-left-style:solid;border-color:white"><div style="display:grid;line-height:170%;width:200px"><span style="font-weight:700;font-size:1.5rem">Dayana Rivera</span><span style="font-size:1rem;letter-spacing:0.05em">Asistente académica</span></div><div style="line-height:18.2px;width:200px;margin-top:9px"><a href="https://api.whatsapp.com/send?phone=51990945941" style="mso-line-height-rule:exactly;text-decoration:none;color:black;font-size:14px;gap:5px;align-items:center;display:flex"><img alt="logo-whatsapp" src="https://archivos-comunes.s3.amazonaws.com/whatsapp.png" width="20" style="display:block;font-size:14px;border:0;outline:none;text-decoration:none"><span style="font-weight:500;font-size:1rem">990 945 941</span></a>
 <a href="https://desarrolloglobal.pe" style="mso-line-height-rule:exactly;text-decoration:none;color:black;font-size:14px;align-items:center;display:flex;gap:5px"><span style="font-weight:400;font-size:1rem">www.desarrolloglobal.pe</span></a></div></td></tr><tr><td colspan="2" style="padding:0;Margin:0"><div style="width:100%;height:2px;background-color:#0057b9"></div></td></tr><tr><td colspan="2" style="padding:0;Margin:0"><div style="text-align:center;display:grid"><img src="https://download-archivos.s3.amazonaws.com/logo-bg-logo.png" width="300" style="display:block;font-size:14px;border:0;outline:none;text-decoration:none;margin-top:5px;margin-bottom:5px" alt=""></div></td></tr></table></td></tr></table></td></tr></table></td></tr></table></td></tr></table>
 <table cellspacing="0" cellpadding="0" align="center" class="es-header" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;width:100%;table-layout:fixed !important;background-color:transparent;background-repeat:repeat;background-position:center top"><tr><td align="center" style="padding:0;Margin:0"><table cellspacing="0" cellpadding="0" bgcolor="#ffffff" align="center" class="es-header-body" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#FFFFFF;width:600px"><tr><td bgcolor="#003399" align="left" background style="padding:20px;Margin:0;background-color:#003399" data-custom-paddings="true"><!--[if mso]><table style="width:560px" cellpadding="0" cellspacing="0"><tr>
<td style="width:270px" valign="top"><![endif]--><table cellspacing="0" cellpadding="0" align="left" class="es-left" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left"><tr><td align="left" class="es-m-p20b" style="padding:0;Margin:0;width:270px"><table width="100%" cellspacing="0" cellpadding="0" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr><td align="center" class="es-m-txt-c" style="padding:0;Margin:0;font-size:0px"><img src="https://ffrbvdx.stripocdn.email/content/guids/CABINET_ecc57152f936766c55ec45db3544c566f45f536a777eae126d096d01b046bf71/images/logodark.png" alt="" width="180" class="img-4199" style="display:block;font-size:14px;border:0;outline:none;text-decoration:none"></td> </tr></table></td></tr></table> <!--[if mso]></td><td style="width:20px"></td>
<td style="width:270px" valign="top"><![endif]--><table cellspacing="0" cellpadding="0" align="right" class="es-right" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:right"><tr><td align="left" style="padding:0;Margin:0;width:270px"><table width="100%" cellspacing="0" cellpadding="0" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr><td align="center" class="es-m-txt-c" style="padding:0;Margin:0;font-size:0px"><table cellspacing="0" cellpadding="0" class="es-table-not-adapt es-social" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr>
<td valign="top" align="center" style="padding:0;Margin:0;padding-right:15px"><a target="_blank" href="https://www.facebook.com/DesarrolloGlobal" style="mso-line-height-rule:exactly;text-decoration:underline;color:#2CB543;font-size:14px"><img title="Facebook" src="https://ffrbvdx.stripocdn.email/content/assets/img/social-icons/logo-white/facebook-logo-white.png" alt="Facebook" width="35" height="35" style="display:block;font-size:14px;border:0;outline:none;text-decoration:none"></a> </td>
<td valign="top" align="center" style="padding:0;Margin:0;padding-right:15px"><a target="_blank" href="https://www.instagram.com/desarrollo_global/" style="mso-line-height-rule:exactly;text-decoration:underline;color:#2CB543;font-size:14px"><img title="Instagram" src="https://ffrbvdx.stripocdn.email/content/assets/img/social-icons/logo-white/instagram-logo-white.png" alt="Instagram" width="35" height="35" style="display:block;font-size:14px;border:0;outline:none;text-decoration:none"></a></td>
 <td valign="top" align="center" style="padding:0;Margin:0;padding-right:15px"><a target="_blank" href="https://www.youtube.com/@desarrolloglobaltv" style="mso-line-height-rule:exactly;text-decoration:underline;color:#2CB543;font-size:14px"><img title="YouTube" src="https://ffrbvdx.stripocdn.email/content/assets/img/social-icons/logo-white/youtube-logo-white.png" alt="YouTube" width="35" height="35" style="display:block;font-size:14px;border:0;outline:none;text-decoration:none"></a></td>
 <td valign="top" align="center" style="padding:0;Margin:0"><a target="_blank" href="https://pe.linkedin.com/company/centro-de-capacitaci%C3%B3n-y-desarrollo-global" style="mso-line-height-rule:exactly;text-decoration:underline;color:#2CB543;font-size:14px"><img title="LinkedIn" src="https://ffrbvdx.stripocdn.email/content/assets/img/social-icons/logo-white/linkedin-logo-white.png" alt="LinkedIn" width="35" height="35" style="display:block;font-size:14px;border:0;outline:none;text-decoration:none"></a></td></tr></table></td></tr></table></td></tr></table><!--[if mso]></td></tr></table><![endif]--></td></tr></table></td></tr></table></td></tr></table></div></body></html>
  `
}
