export default function getTemplateSessionReminder ({ url, typeTime, startSession, dateSession, sessionName, programName, teacherName }: { url: string, id: number, sessionName: string, startSession: string, dateSession: string, programName: string, teacherName: string, emails: string[][], typeTime: 'N' | 'T' }) {
  const typesTime: { [key: string]: string } = {
    N: 'Hoy',
    T: 'Mañana'
  }

  const date = new Date(`${dateSession} ${startSession}`)
  const dateString = date.toLocaleDateString('es-PE', { weekday: 'long', month: 'long', day: 'numeric' })
  const hourString = date.toLocaleTimeString('es-PE', { hour: '2-digit', minute: '2-digit', hour12: true })
  const typeUrl = url.includes('https://meet.google.com') ? 'MEET' : 'ZOOM'
  const info = url.includes('https://meet.google.com')
    ? `Enlace para unirse a la reunion <a target="_blank" href="${url}" style="mso-line-height-rule:exactly;text-decoration:underline;color:#003399;font-size:16px">aquí</a>`
    : 'Si es la primera vez que usas <strong>ZOOM</strong>, puedes descargarlo <a target="_blank" href="https://zoom.us/download" style="mso-line-height-rule:exactly;text-decoration:underline;color:#003399;font-size:16px">aquí</a>'

  return `
<!DOCTYPE html><html dir="ltr" xmlns="http://www.w3.org/1999/xhtml" xmlns:o="urn:schemas-microsoft-com:office:office" lang="es"><head><meta charset="UTF-8"><meta content="width=device-width, initial-scale=1" name="viewport"><meta name="x-apple-disable-message-reformatting"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta content="telephone=no" name="format-detection"><title>Recordatorio Sesión</title> <!--[if (mso 16)]><style type="text/css"> a {text-decoration: none;}  </style><![endif]--><!--[if gte mso 9]><style>sup { font-size: 100% !important; }</style><![endif]--><!--[if gte mso 9]><noscript> <xml> <o:OfficeDocumentSettings> <o:AllowPNG></o:AllowPNG> <o:PixelsPerInch>96</o:PixelsPerInch> </o:OfficeDocumentSettings> </xml> </noscript>
<![endif]--><style type="text/css">.rollover:hover .rollover-first { max-height:0px!important; display:none!important;}.rollover:hover .rollover-second { max-height:none!important; display:block!important;}.rollover span { font-size:0px;}u + .body img ~ div div { display:none;}#outlook a { padding:0;}span.MsoHyperlink,span.MsoHyperlinkFollowed { color:inherit; mso-style-priority:99;}a.es-button { mso-style-priority:100!important; text-decoration:none!important;}a[x-apple-data-detectors],#MessageViewBody a { color:inherit!important; text-decoration:none!important; font-size:inherit!important; font-family:inherit!important; font-weight:inherit!important; line-height:inherit!important;}.es-desk-hidden { display:none; float:left; overflow:hidden; width:0; max-height:0; line-height:0; mso-hide:all;}@media only screen and (max-width:600px) {.es-m-p0r { padding-right:0px!important } .es-m-p20b { padding-bottom:20px!important }
 .es-m-p20 { padding:20px!important } .es-p-default { } *[class="gmail-fix"] { display:none!important } p, a { line-height:150%!important } h1, h1 a { line-height:120%!important } h2, h2 a { line-height:120%!important } h3, h3 a { line-height:120%!important } h4, h4 a { line-height:120%!important } h5, h5 a { line-height:120%!important } h6, h6 a { line-height:120%!important } .es-header-body p { } .es-content-body p { } .es-footer-body p { } .es-infoblock p { } h1 { font-size:30px!important; text-align:left } h2 { font-size:24px!important; text-align:left } h3 { font-size:20px!important; text-align:left } h4 { font-size:24px!important; text-align:left } h5 { font-size:20px!important; text-align:left } h6 { font-size:16px!important; text-align:left } .es-header-body h1 a, .es-content-body h1 a, .es-footer-body h1 a { font-size:30px!important }
 .es-header-body h2 a, .es-content-body h2 a, .es-footer-body h2 a { font-size:24px!important } .es-header-body h3 a, .es-content-body h3 a, .es-footer-body h3 a { font-size:20px!important } .es-header-body h4 a, .es-content-body h4 a, .es-footer-body h4 a { font-size:24px!important } .es-header-body h5 a, .es-content-body h5 a, .es-footer-body h5 a { font-size:20px!important } .es-header-body h6 a, .es-content-body h6 a, .es-footer-body h6 a { font-size:16px!important } .es-menu td a { font-size:14px!important } .es-header-body p, .es-header-body a { font-size:14px!important } .es-content-body p, .es-content-body a { font-size:14px!important } .es-footer-body p, .es-footer-body a { font-size:14px!important } .es-infoblock p, .es-infoblock a { font-size:12px!important } .es-m-txt-c, .es-m-txt-c h1, .es-m-txt-c h2, .es-m-txt-c h3, .es-m-txt-c h4, .es-m-txt-c h5, .es-m-txt-c h6 { text-align:center!important }
 .es-m-txt-r, .es-m-txt-r h1, .es-m-txt-r h2, .es-m-txt-r h3, .es-m-txt-r h4, .es-m-txt-r h5, .es-m-txt-r h6 { text-align:right!important } .es-m-txt-j, .es-m-txt-j h1, .es-m-txt-j h2, .es-m-txt-j h3, .es-m-txt-j h4, .es-m-txt-j h5, .es-m-txt-j h6 { text-align:justify!important } .es-m-txt-l, .es-m-txt-l h1, .es-m-txt-l h2, .es-m-txt-l h3, .es-m-txt-l h4, .es-m-txt-l h5, .es-m-txt-l h6 { text-align:left!important } .es-m-txt-r img, .es-m-txt-c img, .es-m-txt-l img { display:inline!important } .es-m-txt-r .rollover:hover .rollover-second, .es-m-txt-c .rollover:hover .rollover-second, .es-m-txt-l .rollover:hover .rollover-second { display:inline!important } .es-m-txt-r .rollover span, .es-m-txt-c .rollover span, .es-m-txt-l .rollover span { line-height:0!important; font-size:0!important; display:block } .es-spacer { display:inline-table }
 a.es-button, button.es-button { font-size:18px!important; padding:10px 20px 10px 20px!important; line-height:120%!important } a.es-button, button.es-button, .es-button-border { display:inline-block!important } .es-m-fw, .es-m-fw.es-fw, .es-m-fw .es-button { display:block!important } .es-m-il, .es-m-il .es-button, .es-social, .es-social td, .es-menu { display:inline-block!important } .es-adaptive table, .es-left, .es-right { width:100%!important } .es-content table, .es-header table, .es-footer table, .es-content, .es-footer, .es-header { width:100%!important; max-width:600px!important } .adapt-img { width:100%!important; height:auto!important } .es-mobile-hidden, .es-hidden { display:none!important } .es-desk-hidden { width:auto!important; overflow:visible!important; float:none!important; max-height:inherit!important; line-height:inherit!important } tr.es-desk-hidden { display:table-row!important }
 table.es-desk-hidden { display:table!important } td.es-desk-menu-hidden { display:table-cell!important } .es-menu td { width:1%!important } table.es-table-not-adapt, .esd-block-html table { width:auto!important } .h-auto { height:auto!important } .img-4199 { width:200px!important } .es-text-2553 .es-text-mobile-size-16, .es-text-2553 .es-text-mobile-size-16 * { font-size:16px!important; line-height:150%!important } .es-text-5932 .es-text-mobile-size-16, .es-text-5932 .es-text-mobile-size-16 * { font-size:16px!important; line-height:150%!important } .es-text-2639 .es-text-mobile-size-16, .es-text-2639 .es-text-mobile-size-16 * { font-size:16px!important; line-height:150%!important } .img-8032 { width:200px!important } .es-text-6882 .es-text-mobile-size-16, .es-text-6882 .es-text-mobile-size-16 * { font-size:16px!important; line-height:150%!important }
 .es-text-9081 .es-text-mobile-size-16, .es-text-9081 .es-text-mobile-size-16 * { font-size:16px!important; line-height:150%!important } .es-text-2553 .es-text-mobile-size-16.es-override-size, .es-text-2553 .es-text-mobile-size-16.es-override-size * { font-size:16px!important; line-height:150%!important } a.es-button.es-button-1719239913870 { padding:20px!important } a.es-button.es-button-3389 { padding:20px 40px!important } }@media screen and (max-width:384px) {.mail-message-content { width:414px!important } }</style>
 </head> <body class="body" style="width:100%;height:100%;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;padding:0;Margin:0"><div dir="ltr" class="es-wrapper-color" lang="und" style="background-color:#F6F6F6"><!--[if gte mso 9]><v:background xmlns:v="urn:schemas-microsoft-com:vml" fill="t"> <v:fill type="tile" color="#f6f6f6"></v:fill> </v:background><![endif]--><table width="100%" cellspacing="0" cellpadding="0" class="es-wrapper" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;padding:0;Margin:0;width:100%;height:100%;background-repeat:repeat;background-position:center top;background-color:#F6F6F6"><tr><td valign="top" style="padding:0;Margin:0"><table cellspacing="0" cellpadding="0" align="center" class="es-content" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;width:100%;table-layout:fixed !important"><tr>
<td align="center" style="padding:0;Margin:0"><table cellspacing="0" cellpadding="0" bgcolor="#ffffff" align="center" class="es-content-body" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#ffffff;width:600px" role="none"><tr><td align="left" bgcolor="#003399" background style="padding:20px;Margin:0;background-color:#003399" data-custom-paddings="true"><table width="100%" cellspacing="0" cellpadding="0" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr><td valign="top" align="center" class="es-m-p0r es-m-p20b" style="padding:0;Margin:0;width:560px"><table width="100%" cellspacing="0" cellpadding="0" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr>
<td align="center" style="padding:0;Margin:0;font-size:0px"><img src="https://ffrbvdx.stripocdn.email/content/guids/CABINET_ecc57152f936766c55ec45db3544c566f45f536a777eae126d096d01b046bf71/images/logodark.png" alt="logo" width="250" class="img-8032" style="display:block;font-size:14px;border:0;outline:none;text-decoration:none"></td> </tr></table></td></tr></table></td></tr></table></td></tr></table> <table cellspacing="0" cellpadding="0" align="center" class="es-header" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;width:100%;table-layout:fixed !important;background-color:transparent;background-repeat:repeat;background-position:center top"><tr>
<td align="center" style="padding:0;Margin:0"><table cellspacing="0" cellpadding="0" bgcolor="#ffffff" align="center" class="es-header-body" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#FFFFFF;width:600px"><tr><td align="left" data-custom-paddings="true" style="Margin:0;padding-top:40px;padding-right:20px;padding-bottom:40px;padding-left:20px"><table cellpadding="0" cellspacing="0" width="100%" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr><td align="center" valign="top" style="padding:0;Margin:0;width:560px"><table cellpadding="0" cellspacing="0" width="100%" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr>
<td align="left" class="es-text-2553" style="padding:0;Margin:0"><p class="es-text-mobile-size-16 es-override-size" style="Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:27px;letter-spacing:0;color:#333333;font-size:18px"><strong>Estimado estudiante</strong></p> <p class="es-text-mobile-size-16 es-override-size" style="Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:21px;letter-spacing:0;color:#333333;font-size:14px"><br></p><p class="es-text-mobile-size-16 es-override-size" style="Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:24px;letter-spacing:0;color:#333333;font-size:16px">Te recordamos que ${typesTime[typeTime]} <strong>${dateString}</strong>, se llevará a cabo la <strong>${sessionName} </strong>del programa <strong>${programName}</strong></p></td></tr><tr>
<td align="center" class="es-text-9081" style="padding:30px;Margin:0"><p class="es-text-mobile-size-16" style="Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:32px;letter-spacing:0;color:#333333;font-size:16px"><strong>⏰ Hora de inicio: </strong>${hourString}</p> <p class="es-text-mobile-size-16" style="Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:32px;letter-spacing:0;color:#333333;font-size:16px"><strong>👩‍🏫 Docente: </strong>${teacherName}</p></td></tr><tr>
<td align="left" class="es-text-2639" style="padding:0;Margin:0"><p class="es-text-mobile-size-16" style="Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:24px;letter-spacing:0;color:#333333;font-size:16px">Ingresa al aula virtual con tu&nbsp;<strong>correo</strong>&nbsp;y&nbsp;<strong>contraseña</strong>. Luego, busca tu programa y haz clic en&nbsp;<strong>“Ver sesión”</strong>&nbsp;para unirte al <strong>${typeUrl}</strong>.</p></td></tr> <tr>
<td align="center" style="padding:0;Margin:0;padding-top:50px;padding-bottom:50px"><span class="es-button-border es-fw es-m-fw" style="border-style:solid;border-color:#2CB543;background:#003399;border-width:0px 0px 2px 0px;display:block;border-radius:12px;width:auto"><a href="https://aula.desarrolloglobal.pe/aula" target="_blank" class="es-button es-button-1719239913870" style="mso-style-priority:100 !important;text-decoration:none !important;mso-line-height-rule:exactly;color:#FFFFFF;font-size:16px;padding:15px;display:block;background:#003399;border-radius:12px;font-family:arial, 'helvetica neue', helvetica, sans-serif;font-weight:bold;font-style:normal;line-height:19.2px;width:auto;text-align:center;letter-spacing:0;mso-padding-alt:0;mso-border-alt:10px solid #003399">Acceder al Aula Virtual</a></span></td></tr> <tr>
<td align="left" class="es-text-5932" style="padding:0;Margin:0"><p class="es-text-mobile-size-16" style="Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:24px;letter-spacing:0;color:#333333;font-size:16px">${info}.</p><p class="es-text-mobile-size-16" style="Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:24px;letter-spacing:0;color:#333333;font-size:16px"><br>La sala estará abierta 15 minutos antes del inicio. Para cualquier consulta, llámanos o escríbenos a los siguientes números:</p></td></tr> <tr>
<td align="center" class="es-text-6882 es-m-p20" style="padding:10px;Margin:0"><p class="es-text-mobile-size-16" style="Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:32px;letter-spacing:0;color:#333333;font-size:16px">📞 <a target="_blank" href="tel:990945941" style="mso-line-height-rule:exactly;text-decoration:underline;color:#003399;font-size:16px;line-height:32px">990 945 941</a></p><p class="es-text-mobile-size-16" style="Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:32px;letter-spacing:0;color:#333333;font-size:16px">📞 <a href="tel:952379602" target="_blank" style="mso-line-height-rule:exactly;text-decoration:underline;color:#003399;font-size:16px;line-height:32px">952 379 602</a></p></td></tr> <tr>
<td align="center" style="padding:0;Margin:0;padding-top:30px;padding-bottom:30px"><span class="es-button-border es-fw es-m-fw" style="border-style:solid;border-color:#2CB543;background:#003399;border-width:0px 0px 2px 0px;display:block;border-radius:12px;width:auto"><a href="https://vimeo.com/user107307826/review/588026663/b42c672cf2" target="_blank" class="es-button es-button-3389" style="mso-style-priority:100 !important;text-decoration:none !important;mso-line-height-rule:exactly;color:#FFFFFF;font-size:16px;padding:15px 40px;display:block;background:#003399;border-radius:12px;font-family:arial, 'helvetica neue', helvetica, sans-serif;font-weight:bold;font-style:normal;line-height:19.2px;width:auto;text-align:center;letter-spacing:0;mso-padding-alt:0;mso-border-alt:10px solid #003399">¿Cómo ingresar a las sesiones en vivo?</a></span></td></tr></table></td></tr></table></td></tr></table></td> </tr></table>
 <table cellspacing="0" cellpadding="0" align="center" class="es-header" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;width:100%;table-layout:fixed !important;background-color:transparent;background-repeat:repeat;background-position:center top"><tr><td align="center" style="padding:0;Margin:0"><table cellspacing="0" cellpadding="0" bgcolor="#ffffff" align="center" class="es-header-body" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#FFFFFF;width:600px"><tr><td bgcolor="#003399" align="left" background style="padding:20px;Margin:0;background-color:#003399" data-custom-paddings="true"><!--[if mso]><table style="width:560px" cellpadding="0" cellspacing="0"><tr>
<td style="width:270px" valign="top"><![endif]--><table cellspacing="0" cellpadding="0" align="left" class="es-left" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left"><tr><td align="left" class="es-m-p20b" style="padding:0;Margin:0;width:270px"><table width="100%" cellspacing="0" cellpadding="0" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr><td align="center" class="es-m-txt-c" style="padding:0;Margin:0;font-size:0px"><img src="https://ffrbvdx.stripocdn.email/content/guids/CABINET_ecc57152f936766c55ec45db3544c566f45f536a777eae126d096d01b046bf71/images/logodark.png" alt="logo" width="180" class="img-4199" style="display:block;font-size:14px;border:0;outline:none;text-decoration:none"></td> </tr></table></td></tr></table> <!--[if mso]></td><td style="width:20px"></td>
<td style="width:270px" valign="top"><![endif]--><table cellspacing="0" cellpadding="0" align="right" class="es-right" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:right"><tr><td align="left" style="padding:0;Margin:0;width:270px"><table width="100%" cellspacing="0" cellpadding="0" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr><td align="center" class="es-m-txt-c" style="padding:0;Margin:0;font-size:0px"><table cellspacing="0" cellpadding="0" class="es-table-not-adapt es-social" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr>
<td valign="top" align="center" style="padding:0;Margin:0;padding-right:15px"><a target="_blank" href="https://www.facebook.com/DesarrolloGlobal" style="mso-line-height-rule:exactly;text-decoration:underline;color:#2CB543;font-size:14px"><img title="Facebook" src="https://ffrbvdx.stripocdn.email/content/assets/img/social-icons/logo-white/facebook-logo-white.png" alt="Facebook" width="35" height="35" style="display:block;font-size:14px;border:0;outline:none;text-decoration:none"></a> </td>
<td valign="top" align="center" style="padding:0;Margin:0;padding-right:15px"><a target="_blank" href="https://www.instagram.com/desarrollo_global/" style="mso-line-height-rule:exactly;text-decoration:underline;color:#2CB543;font-size:14px"><img title="Instagram" src="https://ffrbvdx.stripocdn.email/content/assets/img/social-icons/logo-white/instagram-logo-white.png" alt="Instagram" width="35" height="35" style="display:block;font-size:14px;border:0;outline:none;text-decoration:none"></a></td>
 <td valign="top" align="center" style="padding:0;Margin:0;padding-right:15px"><a target="_blank" href="https://www.youtube.com/@desarrolloglobaltv" style="mso-line-height-rule:exactly;text-decoration:underline;color:#2CB543;font-size:14px"><img title="YouTube" src="https://ffrbvdx.stripocdn.email/content/assets/img/social-icons/logo-white/youtube-logo-white.png" alt="YouTube" width="35" height="35" style="display:block;font-size:14px;border:0;outline:none;text-decoration:none"></a></td>
 <td valign="top" align="center" style="padding:0;Margin:0"><a target="_blank" href="https://pe.linkedin.com/company/centro-de-capacitaci%C3%B3n-y-desarrollo-global" style="mso-line-height-rule:exactly;text-decoration:underline;color:#2CB543;font-size:14px"><img title="LinkedIn" src="https://ffrbvdx.stripocdn.email/content/assets/img/social-icons/logo-white/linkedin-logo-white.png" alt="LinkedIn" width="35" height="35" style="display:block;font-size:14px;border:0;outline:none;text-decoration:none"></a></td></tr></table></td></tr></table></td></tr></table><!--[if mso]></td></tr></table><![endif]--></td></tr></table></td></tr></table></td></tr></table></div></body></html>
`
}
